#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Email-Simple
Version  : 2.216
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Email-Simple-2.216.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Email-Simple-2.216.tar.gz
Summary  : 'simple parsing of RFC2822 message format and headers'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Email-Simple-man
BuildRequires : perl(Email::Date::Format)

%description
This archive contains the distribution Email-Simple,
version 2.216:
simple parsing of RFC2822 message format and headers

%package man
Summary: man components for the perl-Email-Simple package.
Group: Default

%description man
man components for the perl-Email-Simple package.


%prep
%setup -q -n Email-Simple-2.216

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Email/Simple.pm
/usr/lib/perl5/site_perl/5.26.1/Email/Simple/Creator.pm
/usr/lib/perl5/site_perl/5.26.1/Email/Simple/Header.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Email::Simple.3
/usr/share/man/man3/Email::Simple::Creator.3
/usr/share/man/man3/Email::Simple::Header.3
